#+title: clojure-repl.el: Clojure REPL interaction

*Note:* This documentation is incomplete, may be unreliable, and should be considered as a draft.

This package provides basic interaction with a Clojure subprocess
 (REPL).  It's based on ideas from ~inferior-lisp~ and ~inf-clojure~
 packages.  ~clojure-repl~ provides a set of essential features for
 interactive Clojure development:

- REPL
- Interactive code evaluation
- Print source
- Print documentation
- Macroexpansion
- Run tests
- Automatically load and switch namespace
- Automatically install repl functions
- Print stack trace
- Multiple projects support


*Note:* The package is independent from clojure lsp, but clojure lsp is a
good complement to ~clojure-repl~.

*Note:* Package ~clojure-repl~ evaluate current ~sexp~ instead of ~last sexp~.

* Unwanted effects

* Clojure repl flows

* Emacs flows

* Installation

Currently, the recommended ways to install =clojure-repl= are with
=use-package= and =:vc=, or from a local checkout.

** Install with use-package and vc

#+begin_src emacs-lisp
(use-package clojure-repl
  :vc (:url "https://github.com/vkocubinsky/clojure-repl"
       :rev :newest)
  :hook (clojure-mode . clojure-repl-minor-mode))
#+end_src

* Install from local source checkout

#+begin_src emacs-lisp
(use-package clojure-repl
  :load-path "/path-to-repo/clojure-repl"
  :hook (clojure-mode . clojure-repl-minor-mode))
#+end_src


* Keybinding

** Keybinding for clojure buffer

** Keybinding for REPL buffer


* Configuration

